name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set AWS Credentials
        uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run Gradle Tests
        run: ./gradlew test
